version: "3"
services: 
  redis :
    container_name: redis
    image: redis

  db:
    container_name: db
    image: postgres:9.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  vote:
    container_name: voting-app
    image: voting-app
    ports:
      - 5000:80

  worker:
    container_name: worker-app
    image: worker-app

  result:
    container_name: result-app
    image: result-app
    ports:
      - 5001:80